### ISSUE TITLE
tags.test.ts takes over 30 seconds

### ISSUE THREAD

**Issue by cyrusae** [essential-randomness/AO3.js#13]
Mentioned in Discord but figured documenting it as an issue on here as well would be a good habit to get into.

This is consistent every time I run it; how far over 30s varies (e.g. 35s, 37s) but it's dramatic enough for yarn to be pointing it out (and to make `--watch` miss changes that happen while it's still trying to run the previous round of tests).

**Comment by essential-randomness** [comment]
As discussed on Discord, switching to using msw for tests should help with this: https://mswjs.io/

**Comment by essential-randomness** [comment]
Closed by #19
