### ISSUE TITLE
Add ability to pull Profile pages

### ISSUE THREAD

**Issue by cyrusae** [essential-randomness/AO3.js#2]
- Ability to get information from `https://archiveofourown.org/users/[INSERT USERNAME]/profile` ([astolat as example](https://archiveofourown.org/users/astolat/profile))
- Ability to pull all of it or some selectively (e.g., only user ID) 

Information on profile page: 
- Username
- Pseuds, if any
- Join date
- User ID 
- Bio (can be empty) 
- *May want to include total works for sense of completionism?*

**Comment by cyrusae** [comment]
1. I'm asking for this so that I can use it to build a tool for muting people on ao3 more easily.
2. Currently preventing me from also doing it myself:
- [ ] Can't tell where the information populated in a profile page is stored/under what names before it becomes plain text 
- [ ] Have not been able to tell how existing examples got their own extractable IDs

**Comment by essential-randomness** [comment]
Quick explanation of how AO3.js works, which should help unblock you:

- The entry point is [src/index.ts](https://github.com/essential-randomness/AO3.js/blob/main/src/index.ts). The methods exported there are the "canonical ones" I expect people to use. For now, we only have some related to tags.
- [utils/](https://github.com/essential-randomness/AO3.js/tree/main/src/utils) contains everything related to extracting data from the actual AO3 pages. The methods that fetch the page itself are called `get[X]Page` ([example](https://github.com/essential-randomness/AO3.js/blob/main/src/utils/works.ts#L14)), and take the name of the entity you want to fetch. They use [axios](https://axios-http.com/) to fetch the HTML of the AO3 page, then [cheerio](https://cheerio.js.org/) to load them in a DOM tree for easy traversal. The Cheerio "DOM root" is what's then returned.

  In your case, you'll want a `getAuthorPage(data: {authorName: string}) => {...})` method.
- Each file in utils exports one or more utility methods to extract data from the Page of the corresponding type. Note that each page is typed as [its own extension of CheerioAPI](https://github.com/essential-randomness/AO3.js/blob/main/src/utils/tags.ts#L8) so it cannot be accidentally given to the wrong methods. You'll have to look at the Cheerio documentation to see how the extraction can work, but the high level explanation is that Cheerio is a representation of the HTML of the page, and extracting data in its simplest form it's very similar to using `document.querySelector` in JavaScript. To understand how to extract data from the page, you'll have to look at the HTML (usually with the inspector) and figure out if there's particular IDs, classes or other "landmarks" that you can use.

  See [utils/tags.ts](https://github.com/essential-randomness/AO3.js/blob/main/src/utils/tags.ts#L71), which is the most complete example.

- For getting data from the url itself, i'd build a "`extractAuthorFromUrl`" method, and then pass the result of that to `getAuthorPage`. You're going to extract a name just to then put it back in the URL, which is a bit roundabout, but you can imagine for the most part people might get this author name in many different ways, so you don't want to tie that to already having the URL.
- AO3.js is a prime candidate for Test Driven Development ([example article](https://www.browserstack.com/guide/what-is-test-driven-development)), so I suggest you start by writing tests of what you want to extract from the page, then work to make them pass. [Tests example](https://github.com/essential-randomness/AO3.js/blob/main/src/tests/tags.test.ts#L3). These are in [jest](https://jestjs.io/) and can be run with `yarn run test`.

- You might also want to define an interface to declare the type your method will return. See the definition of [the Tag interface](https://github.com/essential-randomness/AO3.js/blob/main/src/utils/tags.ts#L19).

Let me know if any of this needs further clarification.

**Comment by essential-randomness** [comment]
This is how I'd go about incrementally writing a PR for this. You don't have to follow this to the letter, but it's a good pathway if you want me to review your code incrementally/check your progression/avoid rabbit-holing too early.

- [ ] Write skeleton of types and methods, without implementation
- [ ] Write a small handful of simple test cases
- [ ] Fill the methods to get those simple test cases to pass
- [ ] Write more (failing) tests covering all the complex edge cases that you skipped earlier
- [ ] Iterate on the methods until those pass too

**Comment by cyrusae** [comment]
[Insert "this is probably a stupid question"/"no stupid questions" here] As far as that checklist goes I don't know how to get to a point where I can run tests because I'm not getting my methods into the index correctly but can't tell why not, fwiw

**Comment by cyrusae** [comment]
> Quick explanation of how AO3.js works. . . 

btw: Tried adding this explanation to the README for now #4

**Comment by cyrusae** [comment]
#5 

It's aliiiive
